# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('genderOther', models.CharField(max_length=50, verbose_name='Especifique género')),
                ('ethnicGroup', models.CharField(choices=[('I', 'Indígena'), ('ML', 'Mestizo/Ladino'), ('O', 'Otro')], max_length=2, verbose_name='Grupo étnico')),
                ('ethnicOther', models.CharField(max_length=50, verbose_name='Especifique grupo étnico')),
                ('twitter', models.CharField(max_length=50, verbose_name='Cuenta de twitter @')),
                ('facebook', models.CharField(max_length=200, verbose_name='Página de Facebook')),
                ('maritalStatus', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('UH', 'En unión de hecho'), ('O', 'Otro')], max_length=2, verbose_name='Estado Civil (al momento de presentar la declaración)')),
                ('aspiredPosition', models.CharField(choices=[('EX', 'Ejecutivo'), ('LEG', 'Diputado'), ('M', 'Alcalde')], max_length=3, verbose_name='Posición a la que aspira')),
                ('executivePosition', models.CharField(choices=[('P', 'Presidente'), ('V', 'Vicepresidente')], max_length=1, null=True, verbose_name='Cargo al que aspira')),
                ('seat', models.PositiveSmallIntegerField(null=True)),
                ('email', models.CharField(max_length=300, verbose_name='Correo electrónico')),
                ('celphone', models.CharField(max_length=40, verbose_name='Celular')),
                ('phone', models.CharField(max_length=40, verbose_name='Oficina/Casa')),
                ('webpage', models.CharField(max_length=300, verbose_name='Página Web')),
                ('helpName', models.CharField(max_length=200, verbose_name='Nombres')),
                ('helpLastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('helpEmail', models.CharField(max_length=300, verbose_name='Correo electrónico')),
                ('helpCelphone', models.CharField(max_length=40, verbose_name='Celular')),
                ('authLetter', models.FileField(upload_to='documents/')),
                ('solvencia', models.FileField(upload_to='documents/')),
                ('inAskList', models.BooleanField(default=True, verbose_name='En lista de exige #3de3')),
                ('published', models.BooleanField(default=False, verbose_name='En lista de los que publicaron')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del distrito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Nombre del municipio')),
                ('department', models.CharField(max_length=125, verbose_name='Nombre del departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del partido')),
                ('tType', models.CharField(choices=[('PP', 'Partido Político'), ('CC', 'Comité Civico')], max_length=2, verbose_name='Tipo de entidad')),
                ('shortName', models.CharField(max_length=50, verbose_name='Nombre corto')),
                ('phone', models.CharField(max_length=150, verbose_name='teléfono')),
                ('facebook', models.CharField(max_length=200, verbose_name='Página de Facebook')),
                ('twitter', models.CharField(max_length=50, verbose_name='twitter')),
                ('secretary', models.CharField(max_length=200, verbose_name='Secretario General')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('genderOther', models.CharField(max_length=50, null=True, verbose_name='Especifique género')),
                ('ethnicGroup', models.CharField(choices=[('I', 'Indígena'), ('ML', 'Mestizo/Ladino'), ('O', 'Otro')], max_length=2, verbose_name='Grupo étnico')),
                ('ethnicOther', models.CharField(max_length=50, null=True, verbose_name='Especifique grupo étnico')),
                ('twitter', models.CharField(max_length=50, verbose_name='Cuenta de twitter @')),
                ('facebook', models.CharField(max_length=200, verbose_name='Página de Facebook')),
                ('maritalStatus', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('UH', 'En unión de hecho'), ('O', 'Otro')], max_length=2, verbose_name='Estado Civil (al momento de presentar la declaración)')),
                ('aspiredPosition', models.CharField(choices=[('EX', 'Ejecutivo'), ('LEG', 'Diputado'), ('M', 'Alcalde')], max_length=3, verbose_name='Posición a la que aspira')),
                ('executivePosition', models.CharField(choices=[('P', 'Presidente'), ('V', 'Vicepresidente')], max_length=1, null=True, verbose_name='Cargo al que aspira')),
                ('seat', models.PositiveSmallIntegerField(null=True)),
                ('email', models.CharField(max_length=300, verbose_name='Correo electrónico')),
                ('celphone', models.CharField(max_length=40, verbose_name='Celular')),
                ('phone', models.CharField(max_length=40, verbose_name='Oficina/Casa')),
                ('webpage', models.CharField(max_length=300, null=True, verbose_name='Página Web')),
                ('helpName', models.CharField(max_length=200, null=True, verbose_name='Nombres')),
                ('helpLastname', models.CharField(max_length=200, null=True, verbose_name='Apellidos')),
                ('helpEmail', models.CharField(max_length=300, null=True, verbose_name='Correo electrónico')),
                ('helpCelphone', models.CharField(max_length=40, null=True, verbose_name='Celular')),
                ('authLetter', models.FileField(upload_to='documents/')),
                ('solvencia', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('N', 'Nuevo'), ('C', 'Convertido'), ('BV', 'Verificando'), ('D', 'Descartado')], default='N', max_length=2, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.District')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Municipality')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Party')),
            ],
            options={
                'verbose_name': 'Presentado',
                'verbose_name_plural': 'Presentados',
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.District'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Municipality'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Party'),
        ),
    ]
