# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='ethnicity',
            new_name='ethnicGroup',
        ),
    ]
