# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 04:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190301_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentado',
            name='authLetter',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='presentado',
            name='solvencia',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
