# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190305_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('fieldName', models.CharField(max_length=350, verbose_name='Pregunta')),
                ('fieldValue', models.TextField(null=True, verbose_name='Respuesta')),
                ('formType', models.CharField(choices=[('I', 'Declaración de interés'), ('P', 'Declaración patrimonial')], max_length=1, verbose_name='Formulario')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Candidato')),
            ],
            options={
                'verbose_name': 'DeclarationAnswer',
                'verbose_name_plural': 'DeclarationAnswers',
            },
        ),
    ]
