# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_declarationanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='interestsLine',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='patrimonialLine',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
