# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190315_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.District'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Municipality'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Party'),
        ),
        migrations.AlterField(
            model_name='party',
            name='facebook',
            field=models.CharField(max_length=200, null=True, verbose_name='Página de Facebook'),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(max_length=150, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='party',
            name='secretary',
            field=models.CharField(max_length=200, null=True, verbose_name='Secretario General'),
        ),
        migrations.AlterField(
            model_name='party',
            name='shortName',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre corto'),
        ),
        migrations.AlterField(
            model_name='party',
            name='twitter',
            field=models.CharField(max_length=50, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='presentado',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.District'),
        ),
        migrations.AlterField(
            model_name='presentado',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Municipality'),
        ),
        migrations.AlterField(
            model_name='presentado',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Party'),
        ),
    ]
