version: "3"

services:
    db:
        container_name: 3de3_db
        image: postgres
    backend:
        container_name: 3de3_api
        build: backend
        depends_on:
            - db
    frontend:
        container_name: 3de3_page
        build: frontend
        depends_on:
            - backend
