version: "3"

services:
    db:
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    backend:
        command: gunicorn gt3de3.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./productionMedia:/code/media
            - ./backend/gt3de3/settings_secret.py:/code/gt3de3/settings_secret.py
        expose:
            - 8000
    bnginx:
        container_name: backend_nginx
        build: ./proxy-server/api
        volumes: 
            - ./productionMedia:/usr/src/app/media
            - ./proxy-server/api/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy-server/api/sites/:/etc/nginx/sites-available
        depends_on:
            - backend
        expose:
            - 80
        environment:
            VIRTUAL_HOST: api.3de3.gt
    frontend:
        command: npm run build
        volumes:
            - ./frontend:/app

    fnginx:
        container_name: frontend_nginx
        build: ./proxy-server/webapp
        expose:
            - 80
        environment:
            VIRTUAL_HOST: www.3de3.gt
        volumes:
            - ./frontend/dist:/var/www
            - ./proxy-server/webapp/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy-server/webapp/sites/:/etc/nginx/sites-available
networks:
  default:
    external:
      name: nginx-proxy
