version: "3"

services:
#    db:
#        image: postgres
#    backend:
#        container_name: 3de3_api
#        build: backend
#        command: python manage.py runserver 0.0.0.0:80
#        volumes:
#            - ./backend:/code
#        ports:
#            - "80:80"
#        depends_on:
#            - db
    frontend:
        container_name: 3de3_page
        build: frontend
        command: npm run serve
        volumes:
            - ./frontend:/app
        ports:
            - "80:8080"
